# Generated by Django 4.2.5 on 2023-09-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zlecenia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_wprowadzenia', models.DateField()),
                ('data_rozpoczecia', models.DateField()),
                ('data_zakonczenia', models.DateField()),
                ('opis', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('przebieg', models.IntegerField()),
            ],
            options={
                'db_table': 'zlecenia',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='samochody',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='wlasciciele',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
