# Generated by Django 4.2.5 on 2023-09-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_zlecenia_alter_samochody_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='samochody',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='wlasciciele',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='zlecenia',
            options={'managed': False},
        ),
    ]
